spring:
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
db:
  driver: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/test
  username: jkn897
  password: India@123
  
hibernate:
  dialect:  org.hibernate.dialect.MySQL5Dialect
  show_sql: true
  hbm2ddl:
    auto: update
entitymanager:
  packagesToScan: com
server:
  port: 5050